import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { UserProvider } from "@/context/UserContext";
import { ClipboardsProvider } from "@/context/ClipboardContext";

import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex min-h-screen w-full">
        {/* <Navbar/> */}
        <UserProvider>
        <ClipboardsProvider>
          <Sidebar/>
          <div className="flex-1 w-full ml-64 px-2 bg-gray-600 bg-opacity-80 rounded-lg shadow-lg">
              {children}
          </div>
        </ClipboardsProvider>
        </UserProvider>
    </div>
  );
}
