import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex min-h-screen w-full">
        {/* <Navbar/> */}
        <Sidebar/>
        <div className="ml-64 px-4">
            {children}
        </div>
    </div>
  );
}
