import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex min-h-screen w-full">
        <div className="flex-2 bg-gray-900 flex justify-center items-center h-screen">
            <img src="https://img.freepik.com/free-photo/grunge-black-concrete-textured-background_53876-124541.jpg?semt=ais_hybrid&w=740&q=80" alt="Left Side Image" className="max-w-full max-h-full object-contain" />
        </div>

        <div className="flex-1 bg-gray-800 flex justify-center items-center h-screen">
            <div>
                {/* <h2 className="text-white text-2xl">Login</h2> */}
                {children}
            </div>
        </div>
    </div>
  );
}
